import { NgModule } from "@angular/core";
import {
  MatTableModule,
  MatToolbarModule,
  MatPaginatorModule,
  MatIconModule,
  MatButtonModule,
  MatSortModule,
  MatFormFieldModule,
  MatInputModule,
  MatCardModule,
  MatSnackBarModule,
  MatSidenavModule,
  MatMenuModule,
  MatDividerModule,
  MatDialogModule,
  MatSelectModule,
  MatDatepickerModule,
  MatNativeDateModule,
  MAT_DATE_LOCALE,
  MatExpansionModule,
  MatAutocompleteModule,
  MatProgressBarModule,
  MatStepperModule,
  MatBottomSheetModule,
  MatGridListModule,
  MatButtonToggleModule,
  MatProgressSpinnerModule,
  MatCheckboxModule,
  MatListModule,
  MatBadgeModule,
  MatTabsModule,
  MatPaginatorIntl,
  MatChipsModule,
  MatTooltipModule,
  MatSliderModule
} from "@angular/material";
import { BrowserAnimationsModule } from "@angular/platform-browser/animations";
import { DragDropModule } from "@angular/cdk/drag-drop";

@NgModule({
  imports: [
    BrowserAnimationsModule,
    MatTableModule,
    MatToolbarModule,
    MatTooltipModule,
    MatPaginatorModule,
    MatIconModule,
    MatButtonModule,
    MatSortModule,
    MatFormFieldModule,
    MatInputModule,
    MatCardModule,
    MatSnackBarModule,
    MatSidenavModule,
    MatMenuModule,
    MatDividerModule,
    MatDialogModule,
    MatSelectModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatExpansionModule,
    MatAutocompleteModule,
    MatProgressBarModule,
    MatStepperModule,
    MatGridListModule,
    MatButtonToggleModule,
    MatProgressSpinnerModule,
    MatCheckboxModule,
    MatListModule,
    MatBadgeModule,
    MatTabsModule,
    MatChipsModule,
    DragDropModule,
    MatSliderModule
  ],
  exports: [
    MatTableModule,
    MatToolbarModule,
    MatTooltipModule,
    MatPaginatorModule,
    MatIconModule,
    MatButtonModule,
    MatSortModule,
    MatFormFieldModule,
    MatInputModule,
    MatCardModule,
    MatSnackBarModule,
    MatSidenavModule,
    MatMenuModule,
    MatDividerModule,
    MatDialogModule,
    MatSelectModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatExpansionModule,
    MatAutocompleteModule,
    MatProgressBarModule,
    MatStepperModule,
    MatBottomSheetModule,
    MatGridListModule,
    MatButtonToggleModule,
    MatProgressSpinnerModule,
    MatCheckboxModule,
    MatListModule,
    MatBadgeModule,
    MatTabsModule,
    MatChipsModule,
    DragDropModule,
    MatSliderModule
  ],
  providers: [{ provide: MAT_DATE_LOCALE, useValue: "es-ES" }],
  declarations: []
})
export class AppMaterialModule {}
